### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by mr-tchoo** [z1rk4/Twitter_Giveaway_Bot#1]
Hey, I get this error after entering the username:

Traceback (most recent call last):
  File "C:\Users\User\Documents\PYTHON_PROJECTS\Twitter_Giveaway_Bot-master_Tag_KeywordReply\main.py", line 73, in <module>
    user_tweets = np.array([get_tweets_from_user(handle) for handle in config.account_names])
  File "C:\Users\User\Documents\PYTHON_PROJECTS\Twitter_Giveaway_Bot-master_Tag_KeywordReply\main.py", line 73, in <listcomp>
    user_tweets = np.array([get_tweets_from_user(handle) for handle in config.account_names])
  File "C:\Users\User\Documents\PYTHON_PROJECTS\Twitter_Giveaway_Bot-master_Tag_KeywordReply\main.py", line 37, in get_tweets_from_user
    recent_tweets = [tweet for tweet in tweepy.Cursor(api.user_timeline, id=twitter_handle).items(5) if tweet not in found_tweets and tweet.text.lower()[0:4] != "rt @" and "giveaway" in tweet.text.lower() and "congratulations" not in tweet.text.lower() and "congrats" not in tweet.text.lower()]
  File "C:\Users\User\Documents\PYTHON_PROJECTS\Twitter_Giveaway_Bot-master_Tag_KeywordReply\main.py", line 37, in <listcomp>
    recent_tweets = [tweet for tweet in tweepy.Cursor(api.user_timeline, id=twitter_handle).items(5) if tweet not in found_tweets and tweet.text.lower()[0:4] != "rt @" and "giveaway" in tweet.text.lower() and "congratulations" not in tweet.text.lower() and "congrats" not in tweet.text.lower()]
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\cursor.py", line 47, in __next__
    return self.next()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\cursor.py", line 195, in next
    self.current_page = self.page_iterator.next()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\cursor.py", line 106, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\binder.py", line 250, in _call
    return method.execute()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\binder.py", line 233, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Twitter error response: status code = 404

**Comment by z1rk4** [comment]
You mat 

> Hey, I get this error after entering the username:
> 
> Traceback (most recent call last):
> File "C:\Users\User\Documents\PYTHON_PROJECTS\Twitter_Giveaway_Bot-master_Tag_KeywordReply\main.py", line 73, in 
> user_tweets = np.array([get_tweets_from_user(handle) for handle in config.account_names])
> File "C:\Users\User\Documents\PYTHON_PROJECTS\Twitter_Giveaway_Bot-master_Tag_KeywordReply\main.py", line 73, in 
> user_tweets = np.array([get_tweets_from_user(handle) for handle in config.account_names])
> File "C:\Users\User\Documents\PYTHON_PROJECTS\Twitter_Giveaway_Bot-master_Tag_KeywordReply\main.py", line 37, in get_tweets_from_user
> recent_tweets = [tweet for tweet in tweepy.Cursor(api.user_timeline, id=twitter_handle).items(5) if tweet not in found_tweets and tweet.text.lower()[0:4] != "rt @" and "giveaway" in tweet.text.lower() and "congratulations" not in tweet.text.lower() and "congrats" not in tweet.text.lower()]
> File "C:\Users\User\Documents\PYTHON_PROJECTS\Twitter_Giveaway_Bot-master_Tag_KeywordReply\main.py", line 37, in 
> recent_tweets = [tweet for tweet in tweepy.Cursor(api.user_timeline, id=twitter_handle).items(5) if tweet not in found_tweets and tweet.text.lower()[0:4] != "rt @" and "giveaway" in tweet.text.lower() and "congratulations" not in tweet.text.lower() and "congrats" not in tweet.text.lower()]
> File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\cursor.py", line 47, in **next**
> return self.next()
> File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\cursor.py", line 195, in next
> self.current_page = self.page_iterator.next()
> File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\cursor.py", line 106, in next
> data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
> File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\binder.py", line 250, in _call
> return method.execute()
> File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\binder.py", line 233, in execute
> raise TweepError(error_msg, resp, api_code=api_error_code)
> tweepy.error.TweepError: Twitter error response: status code = 404

You may have entered the wrong credentials into the config file. Check the credentials and let me know if the issue persists.
